In [ ]:
from collections import namedtuple
from math import sqrt

In [1]:
import mysql.connector

dbconfig = {  # для mysql порт по умолчанию 3306
    'host': 'ich-edit.edu.itcareerhub.de',
    'user': 'ich1',
    'password': 'ich1_password_ilovedbs',
    'database': 'ich_edit'
}

connector = mysql.connector.connect(**dbconfig)
# print(connector)
cursor = connector.cursor()
cursor.execute("SELECT * FROM Users")
users_data = cursor.fetchall()  # [(1, Alice, 25), ...]

for user in users_data:
    print(user)  # user ==> (1, Alice, 25)

cursor.close()
connector.close()

(1, 'Alice', 25)
(2, 'Bob', 30)
(3, 'Charlie', 22)
(4, 'David', 28)
(5, 'Eve', 35)
(6, 'Frank', 26)
(7, 'Grace', 31)
(8, 'Hannah', 27)
(9, 'Ivy', 29)
(10, 'Jack', 33)
(11, 'Kate', 23)
(12, 'Liam', 24)
(13, 'Mia', 26)
(14, 'Noah', 28)
(15, 'Olivia', 30)
(16, 'Alice', 30)
(17, 'Bob', 25)
(18, 'Charlie', 35)
(19, 'Alice', 30)
(20, 'Bob', 25)
(21, 'Charlie', 35)
(22, 'Alice', 30)
(23, 'Bob', 25)
(24, 'Charlie', 35)
(25, 'Alice', 30)
(26, 'Bob', 25)
(27, 'Charlie', 35)
(28, 'Alice', 30)
(29, 'Bob', 25)
(30, 'Charlie', 35)
(31, 'Alice', 30)
(32, 'Bob', 25)
(33, 'Charlie', 35)
(34, 'Alice', 30)
(35, 'Bob', 25)
(36, 'Charlie', 35)
(37, 'Alice', 30)
(38, 'Bob', 25)
(39, 'Charlie', 35)
(40, 'Alice', 30)
(41, 'Bob', 25)
(42, 'Charlie', 35)
(46, 'USER 1', 25)
(47, 'USER 2', 30)
(48, 'USER 3', 35)

In [2]:
import mysql.connector

dbconfig = {  # для mysql порт по умолчанию 3306
    'host': 'ich-edit.edu.itcareerhub.de',
    'user': 'ich1',
    'password': 'ich1_password_ilovedbs',
    'database': 'ich_edit'
}

connector = mysql.connector.connect(**dbconfig)
# print(connector)
cursor = connector.cursor(dictionary=True)
cursor.execute("SELECT * FROM Users")
# users_data = cursor.fetchall()  # [(1, Alice, 25), ...] dictionary=None
users_data = cursor.fetchall()  # [{"id": 1, "name": "Alice", "age": 25}, ...] dictionary=True

for user in users_data:
    print(user['name'])  # user ==> (1, Alice, 25)

cursor.close()
connector.close()

Alice
Bob
Charlie
David
Eve
Frank
Grace
Hannah
Ivy
Jack
Kate
Liam
Mia
Noah
Olivia
Alice
Bob
Charlie
Alice
Bob
Charlie
Alice
Bob
Charlie
Alice
Bob
Charlie
Alice
Bob
Charlie
Alice
Bob
Charlie
Alice
Bob
Charlie
Alice
Bob
Charlie
Alice
Bob
Charlie
USER 1
USER 2
USER 3

In [2]:
import pymysql
from pymysql.cursors import DictCursor

dbconfig = {  # для mysql порт по умолчанию 3306
    'host': 'ich-db.ccegls0svc9m.eu-central-1.rds.amazonaws.com',
    'user': 'ich1',
    'password': 'password',
    'db': 'ich_edit',
    'charset': 'utf8mb4',
    'cursorclass':DictCursor
}

# connector = mysql.connector.connect(**dbconfig)
connector = pymysql.connect(**dbconfig)
cursor = connector.cursor()

cursor.execute("SELECT * FROM users")
data = cursor.fetchall()

for user in data:
    print(user)

{'id': 6, 'name': 'Andrey', 'age': 44}
{'id': 7, 'name': 'John', 'age': 25}
{'id': 10, 'name': 'Petr', 'age': 55}
{'id': 11, 'name': 'Jack', 'age': 25}
{'id': 12, 'name': 'Alice', 'age': 30}
{'id': 13, 'name': 'Bob', 'age': 35}
{'id': 14, 'name': 'Alex', 'age': 25}
{'id': 15, 'name': 'Frank', 'age': 25}
{'id': 78, 'name': 'Alex', 'age': 50}
{'id': 83, 'name': 'John', 'age': 25}
{'id': 84, 'name': 'John', 'age': 25}
{'id': 85, 'name': 'Alice', 'age': 30}
{'id': 86, 'name': 'Bob', 'age': 35}
{'id': 95, 'name': 'John', 'age': 25}
{'id': 96, 'name': 'John', 'age': 25}
{'id': 97, 'name': 'Alice', 'age': 30}
{'id': 98, 'name': 'Bob', 'age': 35}
{'id': 99, 'name': 'John', 'age': 25}
{'id': 102, 'name': 'John', 'age': 25}
{'id': 105, 'name': 'John', 'age': 25}
{'id': 106, 'name': 'Elena', 'age': 31}
{'id': 107, 'name': 'John', 'age': 67}
{'id': 108, 'name': 'John', 'age': 25}
{'id': 109, 'name': 'Elena', 'age': 31}
{'id': 114, 'name': 'Max', 'age': 35}
{'id': 115, 'name': 'Anna', 'age': 40}
{'id': 117, 'name': 'Max', 'age': 31}
{'id': 118, 'name': 'Anna', 'age': 40}
{'id': 119, 'name': 'Jenna', 'age': 28}
{'id': 120, 'name': 'Anett', 'age': 42}
{'id': 122, 'name': 'Sarah', 'age': 41}
{'id': 123, 'name': 'Noah', 'age': 25}
{'id': 124, 'name': 'Ariel', 'age': 30}
{'id': 125, 'name': 'Solomon', 'age': 28}
{'id': 126, 'name': 'Ivan', 'age': 26}
{'id': 127, 'name': 'Ali', 'age': 30}
{'id': 128, 'name': 'Bosi', 'age': 35}
{'id': 129, 'name': 'Hanna', 'age': 31}
{'id': 130, 'name': 'Lusya', 'age': 18}
{'id': 131, 'name': 'Ira', 'age': 58}
{'id': 134, 'name': 'Ruslan', 'age': 25}
{'id': 135, 'name': 'Alex', 'age': 31}
{'id': 136, 'name': 'Noah', 'age': 30}
{'id': 137, 'name': 'Ariel', 'age': 35}
{'id': 138, 'name': 'Olga', 'age': 25}
{'id': 139, 'name': 'Mikhail', 'age': 29}
{'id': 140, 'name': 'Ruslan2', 'age': 41}
{'id': 141, 'name': 'Mihail', 'age': 88}
{'id': 142, 'name': 'Svetlana', 'age': 24}
{'id': 143, 'name': 'Katerina', 'age': 30}
{'id': 144, 'name': 'Mashka', 'age': 99}
{'id': 145, 'name': 'John', 'age': 25}
{'id': 150, 'name': 'Vova', 'age': 41}
{'id': 151, 'name': 'Petia', 'age': 25}
{'id': 152, 'name': 'Misha', 'age': 30}
{'id': 153, 'name': 'Dima', 'age': 28}
{'id': 154, 'name': 'Svetlana', 'age': 24}
{'id': 159, 'name': 'John', 'age': 25}
{'id': 160, 'name': 'Alice', 'age': 30}
{'id': 161, 'name': 'Bob', 'age': 35}
{'id': 162, 'name': 'John', 'age': 25}
{'id': 163, 'name': 'Alice', 'age': 30}
{'id': 164, 'name': 'Bob', 'age': 35}
{'id': 165, 'name': 'John', 'age': 25}
{'id': 166, 'name': 'Alice', 'age': 30}
{'id': 167, 'name': 'Bob', 'age': 35}
{'id': 168, 'name': 'John', 'age': 25}
{'id': 169, 'name': 'Alice', 'age': 30}
{'id': 170, 'name': 'Bob', 'age': 35}
{'id': 171, 'name': 'John', 'age': 25}
{'id': 172, 'name': 'Alice', 'age': 30}
{'id': 173, 'name': 'Bob', 'age': 35}
{'id': 174, 'name': 'John', 'age': 25}
{'id': 175, 'name': 'Alice', 'age': 25}
{'id': 176, 'name': 'Alice', 'age': 26}
{'id': 179, 'name': 'Johny', 'age': 20}
{'id': 180, 'name': 'John', 'age': 25}
{'id': 181, 'name': 'Alice', 'age': 30}
{'id': 182, 'name': 'Bob', 'age': 35}
{'id': 183, 'name': 'John', 'age': 25}
{'id': 184, 'name': 'Alice', 'age': 30}
{'id': 185, 'name': 'Bob', 'age': 35}
{'id': 186, 'name': 'John', 'age': 25}
{'id': 187, 'name': 'Alice', 'age': 30}
{'id': 188, 'name': 'Bobby', 'age': 35}
{'id': 189, 'name': 'John', 'age': 25}
{'id': 190, 'name': 'Alice', 'age': 30}
{'id': 191, 'name': 'Bobby', 'age': 35}
{'id': 192, 'name': 'John', 'age': 25}
{'id': 193, 'name': 'Alice', 'age': 30}
{'id': 194, 'name': 'Bobby', 'age': 35}
{'id': 195, 'name': 'John', 'age': 25}
{'id': 196, 'name': 'Alice', 'age': 30}
{'id': 197, 'name': 'Bobby', 'age': 35}
{'id': 201, 'name': 'Pavel', 'age': 11}
{'id': 202, 'name': 'Valera', 'age': 54}
{'id': 203, 'name': 'Olena', 'age': 38}
{'id': 204, 'name': 'Juri', 'age': 41}
{'id': 205, 'name': 'Ippolit', 'age': 98}
{'id': 206, 'name': 'JurijB', 'age': 31}
{'id': 208, 'name': 'Max', 'age': 25}
{'id': 209, 'name': 'Anton', 'age': 30}
{'id': 210, 'name': 'Denis', 'age': 35}
{'id': 211, 'name': 'Alina', 'age': 18}
{'id': 212, 'name': 'Alena', 'age': 19}
{'id': 213, 'name': 'Albina', 'age': 18}
{'id': 214, 'name': 'Akakiy', 'age': 100}
{'id': 215, 'name': 'Fedor', 'age': 55}
{'id': 216, 'name': 'Bobbob', 'age': 35}
{'id': 217, 'name': 'Афанасий', 'age': 34}
{'id': 218, 'name': 'Феофан', 'age': 54}
{'id': 220, 'name': 'Winter', 'age': 50}
{'id': 221, 'name': 'Sommer', 'age': 32}
{'id': 222, 'name': 'Autumn', 'age': 55}
{'id': 223, 'name': 'Lena', 'age': 25}
{'id': 224, 'name': 'Anna', 'age': 30}
{'id': 225, 'name': 'Max', 'age': 35}
{'id': 226, 'name': 'John', 'age': 25}
{'id': 227, 'name': 'John', 'age': 25}
{'id': 228, 'name': 'Alice', 'age': 30}
{'id': 229, 'name': 'Alice', 'age': 30}
{'id': 230, 'name': 'John', 'age': 25}
{'id': 231, 'name': 'Alice', 'age': 30}
{'id': 232, 'name': 'Bob', 'age': 35}
{'id': 233, 'name': 'John', 'age': 25}
{'id': 234, 'name': 'Alice', 'age': 30}
{'id': 235, 'name': 'Bob', 'age': 35}
{'id': 236, 'name': 'Alice', 'age': 30}
{'id': 237, 'name': 'Alice', 'age': 30}
{'id': 241, 'name': 'Slyus', 'age': 25}
{'id': 242, 'name': 'Slyus', 'age': 25}
{'id': 243, 'name': 'Slyus', 'age': 45}
{'id': 259, 'name': 'AGA', 'age': 35}
{'id': 260, 'name': 'John', 'age': 25}
{'id': 261, 'name': 'Alice', 'age': 30}
{'id': 262, 'name': 'Bob', 'age': 35}
{'id': 263, 'name': 'MAX', 'age': 25}
{'id': 264, 'name': 'ANTON', 'age': 30}
{'id': 265, 'name': 'BIBB', 'age': 35}
{'id': 266, 'name': 'AISHA', 'age': 18}
{'id': 272, 'name': 'John', 'age': 25}
{'id': 273, 'name': 'Alice', 'age': 30}
{'id': 274, 'name': 'Bob', 'age': 35}
{'id': 275, 'name': 'John', 'age': 25}
{'id': 276, 'name': 'John', 'age': 25}
{'id': 279, 'name': 'John', 'age': 25}
{'id': 280, 'name': 'Alice', 'age': 30}
{'id': 281, 'name': 'Bob', 'age': 35}
{'id': 282, 'name': 'John', 'age': 25}
{'id': 283, 'name': 'Alice', 'age': 30}
{'id': 284, 'name': 'Bob', 'age': 35}
{'id': 285, 'name': 'John', 'age': 25}
{'id': 286, 'name': 'John', 'age': 25}
{'id': 290, 'name': 'John', 'age': 25}
{'id': 291, 'name': 'Alice', 'age': 30}
{'id': 292, 'name': 'Bob', 'age': 35}
{'id': 293, 'name': 'John', 'age': 25}
{'id': 294, 'name': 'Alice', 'age': 30}
{'id': 295, 'name': 'Bob', 'age': 35}
{'id': 303, 'name': 'John', 'age': 25}
{'id': 304, 'name': 'Alice', 'age': 30}
{'id': 305, 'name': 'Bob', 'age': 35}
{'id': 307, 'name': 'John', 'age': 25}
{'id': 311, 'name': 'John', 'age': 25}
{'id': 312, 'name': 'Alice', 'age': 30}
{'id': 313, 'name': 'Bob', 'age': 35}
{'id': 314, 'name': 'Alice', 'age': 30}
{'id': 315, 'name': 'Bob', 'age': 25}
{'id': 316, 'name': 'Alice', 'age': 30}
{'id': 317, 'name': 'Bob', 'age': 25}
{'id': 854, 'name': 'John', 'age': 25}
{'id': 855, 'name': 'John', 'age': 25}
{'id': 856, 'name': 'Alice', 'age': 30}
{'id': 857, 'name': 'Bob', 'age': 35}
{'id': 858, 'name': 'John', 'age': 25}
{'id': 859, 'name': 'John', 'age': 25}
{'id': 860, 'name': 'Alice', 'age': 30}
{'id': 861, 'name': 'Bob', 'age': 35}
{'id': 865, 'name': 'Baiden', 'age': 82}
{'id': 866, 'name': 'Trump', 'age': 30}
{'id': 867, 'name': 'Bob', 'age': 35}
{'id': 871, 'name': 'Baiden', 'age': 82}
{'id': 872, 'name': 'Trump', 'age': 70}
{'id': 873, 'name': 'Bob Marley', 'age': 35}
{'id': 874, 'name': 'John', 'age': 25}
{'id': 875, 'name': 'John', 'age': 25}
{'id': 876, 'name': 'Alice', 'age': 30}
{'id': 877, 'name': 'Bob', 'age': 35}
{'id': 878, 'name': 'Baiden', 'age': 82}
{'id': 879, 'name': 'Trump', 'age': 30}
{'id': 880, 'name': 'Bob Marley', 'age': 35}
{'id': 881, 'name': 'John', 'age': 25}
{'id': 882, 'name': 'John', 'age': 25}
{'id': 883, 'name': 'Alice', 'age': 30}
{'id': 884, 'name': 'Bob', 'age': 35}
{'id': 885, 'name': 'John', 'age': 25}
{'id': 886, 'name': 'John', 'age': 25}
{'id': 887, 'name': 'Alice', 'age': 30}
{'id': 888, 'name': 'Bob', 'age': 35}
{'id': 889, 'name': 'John', 'age': 25}
{'id': 890, 'name': 'John', 'age': 25}
{'id': 891, 'name': 'Alice', 'age': 30}
{'id': 892, 'name': 'Bob', 'age': 35}
{'id': 893, 'name': 'John', 'age': 25}
{'id': 894, 'name': 'John', 'age': 25}
{'id': 895, 'name': 'Alice', 'age': 30}
{'id': 896, 'name': 'Bob', 'age': 35}
{'id': 897, 'name': 'John', 'age': 25}
{'id': 898, 'name': 'John', 'age': 25}
{'id': 904, 'name': 'John', 'age': 40}
{'id': 905, 'name': 'John', 'age': 30}
{'id': 906, 'name': 'John', 'age': 50}
{'id': 907, 'name': 'John', 'age': 60}
{'id': 908, 'name': 'John', 'age': 60}
{'id': 911, 'name': 'John', 'age': 80}
{'id': 912, 'name': 'John', 'age': 100}
{'id': 956, 'name': 'John', 'age': 25}
{'id': 957, 'name': 'Alice', 'age': 30}
{'id': 958, 'name': 'Bob', 'age': 35}
{'id': 959, 'name': 'John', 'age': 25}
{'id': 960, 'name': 'Alice', 'age': 30}
{'id': 961, 'name': 'Bob', 'age': 35}
{'id': 962, 'name': 'John', 'age': 25}
{'id': 963, 'name': 'Alice', 'age': 30}
{'id': 964, 'name': 'Bob', 'age': 35}
{'id': 968, 'name': 'John', 'age': 25}
{'id': 969, 'name': 'Alice', 'age': 30}
{'id': 970, 'name': 'Bob', 'age': 35}
{'id': 971, 'name': 'John', 'age': 25}
{'id': 972, 'name': 'John', 'age': 25}
{'id': 973, 'name': 'Alice', 'age': 30}
{'id': 974, 'name': 'Bob', 'age': 35}
{'id': 975, 'name': 'John', 'age': 25}
{'id': 976, 'name': 'John', 'age': 25}
{'id': 977, 'name': 'Alice', 'age': 30}
{'id': 978, 'name': 'Bob', 'age': 35}
{'id': 979, 'name': 'John', 'age': 25}
{'id': 980, 'name': 'John', 'age': 25}
{'id': 985, 'name': 'John', 'age': 25}
{'id': 986, 'name': 'John', 'age': 25}
{'id': 987, 'name': 'Amy', 'age': 30}
{'id': 991, 'name': 'Fernando', 'age': 17}
{'id': 992, 'name': 'Lucie', 'age': 20}
{'id': 1004, 'name': 'Franklin', 'age': 45}
{'id': 1005, 'name': 'John', 'age': 25}
{'id': 1006, 'name': 'Alice', 'age': 30}
{'id': 1007, 'name': 'Bob', 'age': 35}
{'id': 1008, 'name': 'Franklin', 'age': 45}
{'id': 1009, 'name': 'Esel', 'age': 15}
{'id': 1010, 'name': 'Shrek', 'age': 40}
{'id': 1011, 'name': 'Fiona', 'age': 28}
{'id': 1012, 'name': 'Franklin', 'age': 45}
{'id': 1013, 'name': 'Esel', 'age': 15}
{'id': 1014, 'name': 'Shrek', 'age': 40}
{'id': 1015, 'name': 'Fiona', 'age': 28}
{'id': 1016, 'name': 'Franklin', 'age': 45}
{'id': 1017, 'name': 'Esel', 'age': 15}
{'id': 1018, 'name': 'Shrek', 'age': 40}
{'id': 1019, 'name': 'Fiona', 'age': 28}
{'id': 1020, 'name': 'Franklin', 'age': 45}
{'id': 1021, 'name': 'Esel', 'age': 15}
{'id': 1022, 'name': 'Shrek', 'age': 40}
{'id': 1023, 'name': 'Fiona', 'age': 28}
{'id': 1030, 'name': 'John', 'age': 25}
{'id': 1038, 'name': 'John', 'age': 25}
{'id': 1039, 'name': 'John', 'age': 25}
{'id': 1040, 'name': 'Alice', 'age': 30}
{'id': 1041, 'name': 'Bob', 'age': 35}
{'id': 1044, 'name': 'John', 'age': 25}
{'id': 1060, 'name': 'John', 'age': 25}
{'id': 1061, 'name': 'John', 'age': 25}
{'id': 1062, 'name': 'John', 'age': 25}
{'id': 1069, 'name': 'John', 'age': 25}
{'id': 1081, 'name': 'John', 'age': 25}
{'id': 1082, 'name': 'John', 'age': 25}
{'id': 1083, 'name': 'John', 'age': 25}
{'id': 1084, 'name': 'John', 'age': 25}
{'id': 1085, 'name': 'Alice', 'age': 30}
{'id': 1086, 'name': 'Bob', 'age': 35}
{'id': 1087, 'name': 'John', 'age': 25}
{'id': 1088, 'name': 'Alice', 'age': 30}
{'id': 1089, 'name': 'Bob', 'age': 35}
{'id': 1090, 'name': 'John', 'age': 25}
{'id': 1091, 'name': 'John', 'age': 25}
{'id': 1092, 'name': 'John', 'age': 25}
{'id': 1093, 'name': 'John', 'age': 25}
{'id': 1094, 'name': 'Alice', 'age': 30}
{'id': 1095, 'name': 'Bob', 'age': 35}
{'id': 1096, 'name': 'John', 'age': 25}
{'id': 1097, 'name': 'Alice', 'age': 30}
{'id': 1098, 'name': 'Bob', 'age': 35}
{'id': 1099, 'name': 'John', 'age': 25}
{'id': 1100, 'name': 'Alice', 'age': 30}
{'id': 1101, 'name': 'Bob', 'age': 35}
{'id': 1102, 'name': 'John', 'age': 25}
{'id': 1103, 'name': 'John', 'age': 25}
{'id': 1105, 'name': 'Alex', 'age': 34}
{'id': 1106, 'name': 'Alex', 'age': 34}
{'id': 1107, 'name': 'Bob', 'age': 18}
{'id': 1126, 'name': 'John', 'age': 25}
{'id': 1127, 'name': 'Alice', 'age': 30}
{'id': 1128, 'name': 'Bob', 'age': 35}
{'id': 1130, 'name': 'John', 'age': 25}
{'id': 1131, 'name': 'Alice', 'age': 30}
{'id': 1132, 'name': 'Bob', 'age': 35}
{'id': 1134, 'name': 'John', 'age': 25}
{'id': 1135, 'name': 'Alice', 'age': 30}
{'id': 1136, 'name': 'Bob', 'age': 35}
{'id': 1138, 'name': 'John', 'age': 25}
{'id': 1139, 'name': 'Alice', 'age': 30}
{'id': 1140, 'name': 'Bob', 'age': 35}
{'id': 1142, 'name': 'John', 'age': 25}
{'id': 1143, 'name': 'Alice', 'age': 30}
{'id': 1144, 'name': 'Bob', 'age': 35}
{'id': 1146, 'name': 'John', 'age': 25}
{'id': 1147, 'name': 'Alice', 'age': 30}
{'id': 1148, 'name': 'Bob', 'age': 35}
{'id': 1150, 'name': 'John', 'age': 25}
{'id': 1151, 'name': 'Alice', 'age': 30}
{'id': 1152, 'name': 'Bob', 'age': 35}
{'id': 1155, 'name': 'John', 'age': 25}
{'id': 1156, 'name': 'Alice', 'age': 30}
{'id': 1157, 'name': 'Bob', 'age': 35}
{'id': 1159, 'name': 'John', 'age': 25}
{'id': 1160, 'name': 'Alice', 'age': 30}
{'id': 1161, 'name': 'Bob', 'age': 35}
{'id': 1163, 'name': 'John', 'age': 25}
{'id': 1164, 'name': 'Alice', 'age': 30}
{'id': 1165, 'name': 'Bob', 'age': 35}
{'id': 1167, 'name': 'John', 'age': 25}
{'id': 1168, 'name': 'Alice', 'age': 30}
{'id': 1169, 'name': 'Bob', 'age': 35}
{'id': 1171, 'name': 'John', 'age': 25}
{'id': 1172, 'name': 'Alice', 'age': 30}
{'id': 1173, 'name': 'Bob', 'age': 35}
{'id': 1206, 'name': 'John', 'age': 25}
{'id': 1207, 'name': 'Alice', 'age': 30}
{'id': 1208, 'name': 'Bob', 'age': 35}
{'id': 1210, 'name': 'John', 'age': 25}
{'id': 1211, 'name': 'Alice', 'age': 30}
{'id': 1212, 'name': 'Bob', 'age': 35}
{'id': 1217, 'name': 'Ганна', 'age': 94}
{'id': 1240, 'name': 'вова', 'age': 10}
{'id': 1241, 'name': 'вова', 'age': 16}
{'id': 1242, 'name': 'вова', 'age': 16}
{'id': 1243, 'name': 'John', 'age': 25}
{'id': 1244, 'name': 'Alice', 'age': 30}
{'id': 1245, 'name': 'Bob', 'age': 35}
{'id': 1246, 'name': 'John', 'age': 25}
{'id': 1247, 'name': 'Alice', 'age': 30}
{'id': 1248, 'name': 'Bob', 'age': 35}
{'id': 1250, 'name': 'вова', 'age': 16}
{'id': 1251, 'name': 'John', 'age': 25}
{'id': 1252, 'name': 'John', 'age': 25}
{'id': 1253, 'name': 'Alice', 'age': 30}
{'id': 1254, 'name': 'Bob', 'age': 35}
{'id': 1255, 'name': 'вова', 'age': 16}
{'id': 1257, 'name': 'вова', 'age': 16}
{'id': 1258, 'name': 'John', 'age': 75}
{'id': 1259, 'name': 'вова', 'age': 16}
{'id': 1260, 'name': 'Вова', 'age': 16}
{'id': 1261, 'name': 'Вова', 'age': 17}
{'id': 1262, 'name': 'John', 'age': 75}
{'id': 1263, 'name': '3', 'age': 75}
{'id': 1265, 'name': '3', 'age': 16}
{'id': 1266, 'name': 'Ivan', 'age': 25}
{'id': 1267, 'name': 'Ivan', 'age': 25}
{'id': 1269, 'name': 'Ivan', 'age': 25}
{'id': 1270, 'name': 'Tom', 'age': 78}
{'id': 1272, 'name': 'AAU', 'age': 25}
{'id': 1273, 'name': 'AAU', 'age': 25}
{'id': 1274, 'name': 'Вова', 'age': 12}
{'id': 1275, 'name': 'AAU', 'age': 25}
{'id': 1276, 'name': 'Dima', 'age': 16}
{'id': 1277, 'name': 'Dima', 'age': 16}
{'id': 1278, 'name': 'Karl', 'age': 16}
{'id': 1279, 'name': 'Dima', 'age': 16}
{'id': 1280, 'name': 'Dima', 'age': 16}
{'id': 1281, 'name': 'Dima', 'age': 16}
{'id': 1282, 'name': 'Вова', 'age': 12}
{'id': 1283, 'name': 'Вова', 'age': 12}
{'id': 1285, 'name': 'Vova', 'age': 16}
{'id': 1286, 'name': 'Vova', 'age': 16}
{'id': 1287, 'name': 'Tom', 'age': 78}
{'id': 1288, 'name': 'John', 'age': 25}
{'id': 1289, 'name': 'Alice', 'age': 30}
{'id': 1290, 'name': 'Bob', 'age': 35}
{'id': 1295, 'name': 'John', 'age': 25}
{'id': 1296, 'name': 'John', 'age': 25}
{'id': 1297, 'name': 'Alice', 'age': 30}
{'id': 1298, 'name': 'Bob', 'age': 35}
{'id': 1307, 'name': 'John-2400', 'age': 25}
{'id': 1308, 'name': 'John-2500', 'age': 25}
{'id': 1309, 'name': 'Alice-2600', 'age': 30}
{'id': 1310, 'name': 'Bob-2700', 'age': 35}
{'id': 1311, 'name': 'John', 'age': 25}
{'id': 1312, 'name': 'Alice', 'age': 30}
{'id': 1313, 'name': 'Bob', 'age': 35}
{'id': 1314, 'name': 'John-24', 'age': 25}
{'id': 1315, 'name': 'John-25', 'age': 25}
{'id': 1316, 'name': 'Alice-26', 'age': 30}
{'id': 1317, 'name': 'Bob-27', 'age': 35}
{'id': 1318, 'name': 'John-24', 'age': 25}
{'id': 1319, 'name': 'John-25', 'age': 25}
{'id': 1320, 'name': 'Alice-26', 'age': 30}
{'id': 1321, 'name': 'Bob-27', 'age': 35}
{'id': 1322, 'name': 'John-24', 'age': 25}
{'id': 1323, 'name': 'John-25', 'age': 25}
{'id': 1324, 'name': 'Alice-26', 'age': 30}
{'id': 1325, 'name': 'Bob-27', 'age': 35}
{'id': 1328, 'name': 'Johnnnn', 'age': 25}
{'id': 1329, 'name': 'John', 'age': 25}
{'id': 1330, 'name': 'John', 'age': 25}
{'id': 1331, 'name': 'John-24', 'age': 25}
{'id': 1332, 'name': 'John-25', 'age': 25}
{'id': 1333, 'name': 'Alice-26', 'age': 30}
{'id': 1334, 'name': 'Bob-27', 'age': 35}
{'id': 1335, 'name': 'John-24', 'age': 25}
{'id': 1336, 'name': 'John-25', 'age': 25}
{'id': 1337, 'name': 'Alice-26', 'age': 30}
{'id': 1338, 'name': 'Bob-27', 'age': 35}
{'id': 1342, 'name': 'Alice', 'age': 30}

In [ ]:
connector = pymysql.connect(**dbconfig)
cursor = connector.cursor()

# cursor.execute("SELECT * FROM users")
# data = cursor.fetchall()

# for user in data:
#     print(user)

name = 'USER 4'
age = 48

cursor.execute(
    "INSERT INTO users (name, age) VALUES (%s, %s)",
    (name, age)
)  # пока commit() явно не будет сделан - изменения будут "висеть" в объекте подключения

connector.commit()

cursor.execute(
    "SELECT * FROM users WHERE name = %s",
    (name,)
)

user_data = cursor.fetchone()
print(user_data)

cursor.close()
connector.close()

In [3]:
connector = pymysql.connect(**dbconfig)
cursor = connector.cursor()

dbconfig = {
    'host': 'ich-edit.edu.itcareerhub.de',
    'user': 'ich1',
    'password': 'ich1_password_ilovedbs',
    'database': '160924_social_blogs',
    'charset': 'utf8mb4',
    'cursorclass': DictCursor
}

In [ ]:
dbconfig = {
    'host': 'ich-edit.edu.itcareerhub.de',
    'user': 'ich1',
    'password': 'ich1_password_ilovedbs',
    'database': '160924_social_blogs',
    'charset': 'utf8mb4',
    'cursorclass': DictCursor
}


connector = pymysql.connect(**dbconfig)
cursor = connector.cursor()
# ACID - A -> Atomicity (Атомарность)

# commit() -> если всё прошло хорошо - коммитим
# rollback() -> если хоть одна операция в транзакции не пройдёт - откатываем всё назад на момент последнего состояния базы данных


moderator_email = "tammy54@yahoo.com"
author_email = "qhayes@gmail.com"
moderator = "moderator"
author = "author"
try:
    cursor.execute(
        """SELECT id
        FROM Role
        WHERE name in (%s, %s)""",
        (moderator, author)
    )

    roles = cursor.fetchall()  # [{...}, {...}]
    print(roles)
    author_role_id = roles[1]['id']
    moderator_role_id = roles[0]['id']

    cursor.execute(
        """
            UPDATE User
            SET role_id = %s
            WHERE email = %s
        """,
        (author_role_id, moderator_email)
    )

    cursor.execute(
        """
            UPDATE User
            SET role_id = %s
            WHERE email = %s
        """,
        (moderator_role_id, author_email)
    )

    if cursor.rowcount == 0:
        raise ValueError("Update failed; no rows affected.")
    connector.commit()

    cursor.execute(
        """
            SELECT email, role_id
            FROM User
            WHERE email IN (%s, %s)
        """,
        (moderator_email, author_email)
    )

    data = cursor.fetchall()

    print(data)

except pymysql.Error as e:
    print("[Database ERROR]:", e)
    connector.rollback()
except Exception as e:
    print("[Exception]:", e)
    connector.rollback()
finally:
    cursor.close()
    connector.close()

In [ ]:
import pymysql
from pymysql.cursors import DictCursor

 
dbconfig = {
'host': 'ich-edit.edu.itcareerhub.de',
'user': 'ich1',
'password': 'ich1_password_ilovedbs',
'database': '160924_social_blogs'
 
}

connector = pymysql.connect(**dbconfig)
cursor = connector.cursor(dictionary = True)

cursor.execute(""" SELECT * FROM User WHERE role_id = %s""")

In [ ]:
import mysql.connector

dbconfig = {
'host': 'ich-edit.edu.itcareerhub.de',
'user': 'ich1',
'password': 'ich1_password_ilovedbs',
'database': '160924_social_blogs',
}

connector = mysql.connector.connect(**dbconfig)
cursor = connector.cursor(dictionary=True)

cursor.execute(
    """select * from User where 
    role_id = %s
    """,
    (
        2,
    )
)

required = cursor.fetchall()

for user in required:
    print(user)

cursor.close()
connector.close()